import Head from "next/head";
import Blogs from "./blogs";
import { useEffect, useState } from "react";
import Pagination from "@/components/pagination";
import LightBox from "@/components/LightBox";

export default function Home() {
  const [blogsData, setBlogsData] = useState([]);
  const [searchValue, setSearchValue] = useState("");
  const [page, setPage] = useState(1);
  const [clickedBlog, setClickedBlog] = useState(null);

  useEffect(() => {
    const fetchArticles = async () => {
      try {
        const res = await fetch(
          "https://api.theinnerhour.com/v1/customers/resources/articles/list?page=1&limit=10"
        );
        const jsonData = await res.json();
        console.log("data", jsonData);
        setBlogsData(jsonData.data);
      } catch (err) {
        console.error(err);
      }
    };
    fetchArticles();
  }, []);

  const filterdArray = blogsData.filter((currItem) =>
    currItem.short_description.includes(searchValue)
  );

  const handleClick = (item) => {
    console.log(item);
    setClickedBlog(item);
  };

  return (
    <div>
      <Head>
        <title>Abhishek`s Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-200 ">
        {/*  search functionality starts */}
        <div className="w-full  flex justify-around pt-10">
          {searchValue ? (
            <p></p>
          ) : (
            <h2 className="font-semibold">All articles</h2>
          )}
          <h1></h1>
          <input
            placeholder="search articles              🔍"
            className="p-2 text-left  bg-gray-100"
            value={searchValue}
            onChange={(e) => setSearchValue(e.target.value)}
          />
        </div>
        {searchValue ? (
          <h1 className="  ml-40">Search results for: {searchValue}</h1>
        ) : (
          ""
        )}

        {/*  search functionality ends */}

        {filterdArray.length === 0 ? (
          <h3 className="flex justify-center p-72 text-gray-600 ">
            No Article Found
          </h3>
        ) : (
          <>
            <div className=" mx-auto max-w-2xl  px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
              <div className=" ml-11 grid grid-cols-4 gap-y-10 gap-x-6  sm:grid-cols-2   lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                {filterdArray.slice(page * 20 - 20, page * 20).map((elem) => (
                  <span key={elem.id} onClick={() => handleClick(elem)}>
                    <Blogs
                      blogUrl={elem.thumb}
                      title={elem.title}
                      description={elem.short_description}
                      id={elem.id}
                      slug={elem.slug}
                    />
                  </span>
                ))}
              </div>
            </div>
            <Pagination
              page={page}
              setPage={setPage}
              totalBlogs={filterdArray}
            />
            <div>
              {clickedBlog && (
                <LightBox
                  clickedBlog={clickedBlog}
                  setClickedBlog={setClickedBlog}
                />
              )}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
